# Generated by Django 3.2.12 on 2024-01-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isBorrowed',
            field=models.BooleanField(default=False),
        ),
    ]
